project_id = "tbmcmbldoaespjlhpfys"

[functions.ai-assistant-chat]
verify_jwt = false

[functions.calculate-cost-sheet]
verify_jwt = true

[functions.submit-cost-sheet-approval]
verify_jwt = true

[functions.approve-cost-sheet]
verify_jwt = true

[functions.apply-cost-sheet-rates]
verify_jwt = true

[functions.submit-quote-approval]
verify_jwt = true

[functions.send-quote-to-customer]
verify_jwt = true