// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbmcmbldoaespjlhpfys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRibWNtYmxkb2Flc3BqbGhwZnlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTQzMzcsImV4cCI6MjA2OTM5MDMzN30.4uJ4xpyZENd15IPQ-ctaouZ0Q7HFNr-CsRtJ0O7bqNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});